{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vsphere-passthrough-node-controller.fullname" . }}
  labels:
    {{- include "vsphere-passthrough-node-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vsphere-passthrough-node-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vsphere-passthrough-node-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
