{{- if and (not .Values.vcenter.existingSecret) .Values.vcenter.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vsphere-passthrough-node-controller.vcenterSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vsphere-passthrough-node-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  VCENTER_HOST: {{ .Values.vcenter.host | quote }}
  VCENTER_USER: {{ .Values.vcenter.user | quote }}
  VCENTER_PASSWORD: {{ .Values.vcenter.password | quote }}
{{- end }}
